version: '3'
services:

    prometheus:
        image: prom/prometheus:latest
        container_name: prometheus
        volumes: 
          - "./conf/prometheus.yaml:/etc/prometheus/prometheus.yaml"
        ports:
          - "9090:9090"
        command:
          - "-config.file=/etc/prometheus/prometheus.yaml"

    alertmanager:
        image: prom/alertmanager:latest
        container_name: alertmanager
        # volumes: 
        #   - "./conf/alert-manager.yaml:/etc/alertmanager/config.yml"
        ports:
         - "9093:9093"
        # command:
        #  - "-config.file=/etc/alertmanager/alert-manager.yaml"

    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        ports:
          - "9100:9100"

    grafana:
        image: grafana/grafana:latest
        container_name: grafana
        ports:
          - "3000:3000"

    cadvisor:
        image: google/cadvisor:latest
        container_name: cadvisor
        volumes:
          - "/:/rootfs:ro"
          - "/var/run:/var/run:rw"
          - "/sys:/sys:ro"
          - "/var/lib/docker/:/var/lib/docker:ro"
        privileged: true
        ports:
          - "8080:8080"