Vagrant.configure("2") do |config|

  config.vm.define "web" do |web|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.network :forwarded_port, guest: 80, host: 4567, auto_correct: true
  config.vm.network "public_network", bridge: "en0: Wi-Fi (AirPort)"
  config.vm.synced_folder "./syncFolder", "/syncFolder", disabled: false
  config.vm.synced_folder "./syncFolder/nginx/conf", "/etc/nginx/sites-available", create: true, disabled: false
  config.vm.synced_folder "./syncFolder/html", "/var/www/html", create: true,
   owner: "www-data", group: "www-data", disabled: false
  end
  
  config.vm.define "db" do |db|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provision :shell, path: "bootstrap_sql.sh"
  config.vm.network "private_network", ip: "10.0.2.100"
  config.vm.synced_folder "./syncFolder/mysqlData", "/var/lib/mysql", create: true, disabled: true
  end

end