version: '3'

networks:
   lpicot:
      external: true

services:
   syslog:
      image: fabriziogaliano/docker-rsyslog:v8.18.0

      container_name: syslog

      volumes: 
         - "./syslog/conf/rsyslog.conf:/etc/rsyslog.conf"
         - "./syslog/conf.d/:/etc/rsyslog.d"
         - "./syslog/log:/var/log"

      networks:
         - lpicot

      ports:
         - "514:514/udp"

   logstash:
      image: docker.elastic.co/logstash/logstash:5.5.2

      container_name: logstash

      volumes:
         - "./logstash/log:/var/log"
         - "./logstash/conf/custom.conf:/usr/share/logstash/config/custom.conf"
         - "./logstash/conf/logstash.yaml:/usr/share/logstash/config/logstash.yaml"

      networks:
         - lpicot

      ports:
         - "5000:5000"
         - "5514:5514/udp"

   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0

      container_name: elasticsearch

      volumes:
         - "./elasticsearch/data:/usr/share/elasticsearch/data"

      environment:
         - 'transport.host=127.0.0.1'
         - 'http.host=0.0.0.0'
      #    - 'cluster.name=lpicot-cluster'
      #    - 'bootstrap.memory_lock=true'
      #    - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
         - 'xpack.security.enabled=false'

      networks:
         - lpicot

      ports:
         - "9200:9200"
         - "9300:9300"
   kibana:
      image: docker.elastic.co/kibana/kibana:5.4.0

      container_name: kibana

      volumes:
         - "./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml"

      environment:
         SERVER_NAME: lpicot.lab.local
         ELASTICSEARCH_URL: http://elasticsearch:9200
      #    XPACK_MONITORING_ENABLED: false

      networks:
         - lpicot

      ports:
         - "5601:5601"

   nginx: 
      image: nginx:1.13.3-alpine

      container_name: nginx

      networks:
         - lpicot

      ports:
         - "8088:80"

      logging:
          driver: syslog
          options:
            tag: lpicot/logstash-nginx
            syslog-address: "udp://10.2.1.21:514"
